imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.recipe_images: /uploads/images/recipe
  
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true    
    translator: {fallbacks: ["%locale%"] }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
vich_uploader:
    db_driver: orm
    mappings:
        recipe_images:
            uri_prefix:         %app.path.recipe_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/recipes
            
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        finder: ~
        app:
            types:
                Ingredient:
                    mappings:
                        id: ~
                        name: ~
                        createdAt: ~
                    persistence:
                        driver: orm
                        model:  Ant\RecipeBundle\Entity\Ingredient
                        
                Recipe:
                    mappings:
                        id: ~
                        name: ~
                        descripcion: ~
                        elaboracion: ~
                        time: ~
                        image: ~
                        imageFile: ~
                        updatedAt: ~
                        category: ~
                        slug: ~
                        pathVideo: ~
                        diners: ~
                    persistence:
                        driver: orm
                        model:  Ant\RecipeBundle\Entity\Recipe 
                        
                RecipeIngredient:
                    mappings:
                        id: ~
                        quantity: ~
                        mandatory: ~
                        ingredient: ~
                        recipe: ~
                    persistence:
                        driver: orm
                        model:  Ant\RecipeBundle\Entity\RecipeIngredient

                        
            
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                thumbnail:    { size: [200, 200], mode: outbound }
                
        new_thumb:
            
            quality: 75
            
            filters:
                
                thumbnail: { size: [200, 200], mode: outbound }                
                
knp_paginator:
    page_range: 5
    default_options:
        page_name:           page
        sort_field_name:     sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination:          KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable:            KnpPaginatorBundle:Pagination:sortable_link.html-twig
            
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Ant\RecipeBundle\Entity\User
    
easy_admin:
    entities:
        Recipe:
            class: Ant\RecipeBundle\Entity\Recipe
            label: 'Recipe'
            list:
               title: "Recetas"
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'}
                   - { property: 'descripcion', type: 'text'}
                   - { property: 'elaboracion', type: 'text'}
                   - { property: 'image', type: 'image', base_path: '%app.path.recipe_images%'}
                   - { property: 'time'}
                   - { property: 'category', type: 'text'}
                   - { property: 'slug', type: 'text'}
                   - { property: 'path_video', type: 'text'}
                   - { property: 'diners', type: 'integer'}
            show:
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'}
                   - { property: 'descripcion', type: 'text'}
                   - { property: 'elaboracion', type: 'text'}
                   - { property: 'image', type: 'image', base_path: '%app.path.recipe_images%'}
                   - { property: 'time'}
                   - { property: 'category', type: 'text'}
                   - { property: 'slug', type: 'text'}
                   - { property: 'path_video', type: 'text'}
                   - { property: 'diners', type: 'integer'}
            form:
               title: "Create/edit recipes"
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'} 
                   - { property: 'descripcion', type: 'textarea'}
                   - { property: 'elaboracion', type: 'ckeditor'}
                   - { property: 'imageFile', type: 'vich_image'}
                   - { property: 'time'}
                   - { property: 'category', type: 'text'}
                   - { property: 'slug', type: 'text'}
                   - { property: 'path_video', type: 'text'}
                   - { property: 'diners', type: 'integer'}
        Ingredient:
            class: Ant\RecipeBundle\Entity\Ingredient
            label: 'Ingredient'
            list:
               title: "Ingredientes"
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'}
                   - { property: 'created_at', type: 'datetime'}
            show:
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'}
                   - { property: 'created_at', type: 'datetime'}                       
            form:
               title: "Create/edit ingredients"
               fields: 
                   - 'id'
                   - { property: 'name', type: 'text'}
                   - { property: 'created_at', type: 'datetime'}               
        RecipeIngredient:
            class: Ant\RecipeBundle\Entity\RecipeIngredient
            label: 'RecipeIngredient'
            list:
                title: "Relación"
                fields: 
                    - 'id'
                    - { property: 'ingredient'}
                    - { property: 'recipe'}
                    - { property: 'quantity', type: 'integer'} 
                    - { property: 'mandatory'}
            show:
                title: "Relación"
                fields:
                    - 'id'
                    - { property: 'ingredient_id', type: 'integer'}
                    - { property: 'recipe_id', type: 'integer'}
                    - { property: 'quantity', type: 'integer'} 
                    - { property: 'mandatory', type: 'boolean'}
            form:
                title: "Create/Edit relations"
                fields:
                    - 'id'
                    - { property: 'ingredient'}
                    - { property: 'recipe'}
                    - { property: 'quantity', type: 'integer'} 
                    - { property: 'mandatory'}
                     
    list:
        max_results: 25

    design:
        brand_color:  'orange'
        color_scheme: 'light'
    
        

            